#!/bin/sh

if [ $# == 0 ]; then
  echo usage: decrypt file ...
  exit 1
fi

echo enter key:
read -s key1

if [ "$key1" == "" ]; then
  echo key is empty
  exit 1
fi

for file in $@; do
  echo $file
  crypto decrypt -key $key1 -nopreserve $file
done

